window.SNOW_PROJECTS = [ {
    id: "vertexa-odds",
    title: "VERTEXA ODDS",
    sub: "Arbitrage and bankroll management platform",
    kind: "WEB APP",
    year: "2026",
    meta: "PRODUCT DESIGN · DEVELOPMENT · WEB APP",
    img: "assets/posters/vertexaodds.png",
    lockCrop: { x: .50, y: .12, width: .43, height: .70 },
    accent: "#ff6a16",
    lockTone: "dark",
    desktopUrl: "vertexaodds.com",
    link: "projects/vertexa-odds",
    vertical: false,
    featured: true
}, {
    id: "ggmax",
    title: "GGMAX",
    sub: "Public marketplace profile",
    kind: "PROFILE",
    year: "2023",
    meta: "MARKETPLACE · PUBLIC RECORD",
    img: "assets/posters/ggmax-profile.png",
    lockCrop: { x: .045, y: .055, width: .43, height: .71 },
    accent: "#0879f9",
    lockTone: "light",
    desktopUrl: "ggmax.com.br/perfil/bysnow",
    screenCrop: { x: .035, y: .05, width: .72, height: .72 },
    screenFilter: "brightness(.92) contrast(1.10) saturate(1.05)",
    link: "projects/ggmax",
    vertical: false
}, {
    id: "pendly",
    title: "PENDLY",
    sub: "Reminder system absorbed by Vertexa Odds",
    kind: "ARCHIVED",
    year: "2025",
    meta: "REMINDERS · TASKS · ORGANIZATION",
    img: null,
    link: "projects/pendly",
    vertical: false
}, {
    id: "staytrackd",
    title: "STAYTRACKD",
    sub: "em desenvolvimento.",
    kind: "EM DESENVOLVIMENTO.",
    year: "2026",
    meta: "EM DESENVOLVIMENTO.",
    img: null,
    link: "projects/staytrackd",
    vertical: false
} ];
